changed name to NUXT_ENV_TZPRO_URL
lousando/briskett pull request #21
Opened 2023-11-21 17:04 UTC by GajendraR

changed name of env variable to NUXT_ENV_TZPRO_URL 
issue_number - #20

2023-11-21 23:27 UTC, lousando requested changes
Thank you for your help :)
I just request one change please so I can merge this :)

2023-11-22 06:44 UTC, GajendraR commented on .env.example
> +NUXT_ENV_TZPRO_API_KEY=" https://docs.tzpro.io/intro/access"
ok

2023-11-22 06:59 UTC, GajendraR commented on .env.example
> +NUXT_ENV_TZPRO_API_KEY=" https://docs.tzpro.io/intro/access"
I have set NUXT_ENV_TZPRO_API_KEY to an empty value and included the URL as a comment.

2023-11-22 15:23 UTC, lousando approved these changes

2023-11-22 15:24 UTC, merged